# CI-specific overrides to reduce memory usage
services:
  db:
    deploy:
      resources:
        limits:
          memory: 512M
    command: postgres -c shared_buffers=128MB -c max_connections=50

  redis:
    deploy:
      resources:
        limits:
          memory: 128M

  api:
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  test:
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - POSTGRES_USER=appuser832jdsf
      - POSTGRES_PASSWORD=app.password832jdsf
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_SERVER=db
      - JWT_SECRET_KEY=vka6tYama.FYAMUqjQYNzXtqCs7ZeibGHN_nxEqNtEkwQ*aPnvcRT_oowuuKw-zjXdHWqbZVd4A_hGXukU6DgztzZcjZ9FwydZ-4
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - PYTHONPATH=/app
      - TESTING=True
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=admin123
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    deploy:
      resources:
        limits:
          memory: 512M