"""Add UUID to organizations

Revision ID: c9a6a41b34e5
Revises: 439a847c88cc
Create Date: 2025-07-20 08:56:03.544152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9a6a41b34e5'
down_revision: Union[str, None] = '439a847c88cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add UUID column as nullable first
    op.add_column('organizations', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Generate UUIDs for existing organizations
    op.execute("""
        UPDATE organizations 
        SET uuid = gen_random_uuid() 
        WHERE uuid IS NULL
    """)
    
    # Now make it non-nullable
    op.alter_column('organizations', 'uuid', nullable=False)
    
    # Create unique index
    op.create_index(op.f('ix_organizations_uuid'), 'organizations', ['uuid'], unique=True)
    
    # Other auto-generated changes - commenting out unrelated changes
    # op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    # op.drop_constraint(op.f('permissions_name_key'), 'permissions', type_='unique')
    # op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    # op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    # op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    # op.drop_column('site_modules', 'version_updated_at')
    # op.drop_index(op.f('uq_user_default_org'), table_name='user_organizations', postgresql_where='(is_default = true)')
    # op.drop_constraint(op.f('user_roles_user_id_role_id_organization_id_key'), 'user_roles', type_='unique')
    # op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_uuid'), table_name='organizations')
    op.drop_column('organizations', 'uuid')
    # ### end Alembic commands ###
