"""Add description field to sites table

Revision ID: f83633f2fa86
Revises: dc0a14d7a7da
Create Date: 2025-07-17 09:16:29.764316

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f83633f2fa86"
down_revision: Union[str, None] = "dc0a14d7a7da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites", "description")
    # ### end Alembic commands ###
